2021-11-03 17:25:13,541 INFO    MainThread:28989 [internal.py:wandb_internal():88] W&B internal server running at pid: 28989, started at: 2021-11-03 17:25:13.541171
2021-11-03 17:25:13,552 DEBUG   HandlerThread:28989 [handler.py:handle_request():130] handle_request: check_version
2021-11-03 17:25:13,554 DEBUG   SenderThread:28989 [sender.py:send():185] send: header
2021-11-03 17:25:13,554 DEBUG   SenderThread:28989 [sender.py:send_request():199] send_request: check_version
2021-11-03 17:25:13,555 INFO    WriterThread:28989 [datastore.py:open_for_write():77] open: /Users/sjhuang/Documents/docs/image_classifier/wandb/run-20211103_172512-30hjuyjc/run-30hjuyjc.wandb
2021-11-03 17:25:16,140 WARNING MainThread:28989 [internal.py:wandb_internal():147] Internal process interrupt: 1
2021-11-03 17:25:17,284 WARNING MainThread:28989 [internal.py:wandb_internal():147] Internal process interrupt: 2
2021-11-03 17:25:17,285 ERROR   MainThread:28989 [internal.py:wandb_internal():150] Internal process interrupted.
2021-11-03 17:25:17,559 INFO    HandlerThread:28989 [handler.py:finish():731] shutting down handler
2021-11-03 17:25:17,566 INFO    WriterThread:28989 [datastore.py:close():281] close: /Users/sjhuang/Documents/docs/image_classifier/wandb/run-20211103_172512-30hjuyjc/run-30hjuyjc.wandb
2021-11-03 17:25:18,561 INFO    SenderThread:28989 [sender.py:finish():1029] shutting down sender
2021-11-03 17:25:18,562 INFO    MainThread:28989 [internal.py:handle_exit():78] Internal process exited
